### ISSUE TITLE
師傅您好，煩請看下這個報錯原因。

### ISSUE THREAD

**Issue by 98Kstar** [bigblackhat/oFx#2]
oFx git:(main) ✗ python3 ofx.py 
Traceback (most recent call last):
  File "/root/tool/批量扫描/oFx/ofx.py", line 21, in <module>
    from lib.core.common import get_local_version
  File "/root/tool/批量扫描/oFx/lib/core/common.py", line 17, in <module>
    from lib.core.log import logverifyerror,logvuln,logunvuln
  File "/root/tool/批量扫描/oFx/lib/core/log.py", line 40, in <module>
    STREAM_HANDLE.setLevel(logging.DEBUG)
AttributeError: 'NoneType' object has no attribute 'setLevel'

**Comment by bigblackhat** [comment]
我看了下，之前确实有一处代码运行的可能我没考虑到，感谢指出，我在2.17.2版本中尝试修复这个缺陷，已经发布了，你可以下这个最新版试试，应该没问题了
